site:
  title: Watchdog Manual
  url: https://leamas.github.io/ocpn-manuals/
  start_page:  watchdog:ROOT:watchdog.adoc

content:
  sources:
    - url: https://github.com/rgleason/watchdog_pi.git
      branches: master
      edit_url: true
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
	